export const GET_PAINTINGS = 'GET_PAINTINGS';
export const GET_PAINTINGS_SUCCESSFUL = 'GET_PAINTINGS_SUCCESSFUL';
export const GET_PAINTINGS_FAILED = 'GET_PAINTINGS_FAILED';

export const GET_PAINTING_DETAILS = 'GET_PAINTING_DETAILS';
export const GET_PAINTING_DETAILS_SUCCESSFUL = 'GET_PAINTING_DETAILS_SUCCESSFUL';
export const GET_PAINTING_DETAILS_FAILED = 'GET_PAINTING_DETAILS_FAILED';
export const GET_PAINTING_DETAILS_RESET = 'GET_PAINTING_DETAILS_RESET';


